[package]
name = "localsend"
version = "0.1.0"
authors = ["Krithic Kumar krithickumarub@protonmail.com"]
edition = "2021"
license = "GPL-3.0"
readme = "README.md"
keywords = ["filesharing"]
categories = ["command-line-utilities"]
description = "a CLI for localsend"
repository = "https://github.com/notjedi/localsend-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
localsend-core = { path = "crates/localsend-core", package = "localsend-core" }
tokio = { version = "1.26.0", features = ["full"] }
log = "0.4.17"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[workspace]
members = [
    "crates/localsend-core",
    "crates/axum-server",
    "crates/rustls",
]
